ngrok/src/session.rs

Some things got broken when CI wasn't running (whoops).

ci: get all of the checks green again

---

ngrok/src/session.rs

This came out of the first api review. We could probably still separate out "configuration" errors from "connection" errors and make them two distinct steps, but this at least makes the current approach consistent for now.

session: move server name errors to connect time

---

ngrok/Cargo.toml
ngrok/src/session.rs
ngrok/src/tunnel.rs

Probably gonna split out the protocol-level changes, but basic reconnecting is working. Probably some bugs still.

ngrok: automatically reconnect the session on errors

---

muxado/src/stream_manager.rs

Muxado is noisy - lower everything to debug or lower.

muxado: lower the level of some evens/spans

---

.github/workflows/ci.yml
flake.nix

Resolves #11 
This should help prevent any local/CI mismatch that keeps putting me on the receiving end of a clippy smackdown :grin:

ci: use nix to install tools

---

muxado/Cargo.toml
ngrok/Cargo.toml
ngrok/src/tunnel.rs
ngrok/src/tunnel_ext.rs

Also a bit of feature groundwork for the online tests.

features: make the hyper and axum support optional

---

.github/workflows/ci.yml
flake.nix
ngrok/Cargo.toml
ngrok/src/lib.rs
ngrok/src/online_tests.rs

These tests will verify this crate against the live ngrok servers, and should mirror the online tests in `ngrok-go`.

online testing

---

ngrok/README.md

Update readme for application type

---

.github/workflows/ci.yml

This sed replaces the curl in the install.sh before handing to bash.

sed curl to cover uses inside install.sh

---

.github/workflows/ci.yml
.github/workflows/rust-cache/action.yml
.github/workflows/sccache/action.yml
flake.nix

More CI caching!
No sccache for the tests with the github-provided stable toolchain, but that should be offset by the lack of direnv setup time.

ci: add sccache

---

.github/workflows/ci.yml
Cargo.toml
cargo-doc-ngrok/Cargo.toml
cargo-doc-ngrok/LICENSE-APACHE
cargo-doc-ngrok/LICENSE-MIT
cargo-doc-ngrok/src/main.rs

Pretty bare-bones for now - builds the docs and serves them up via an ngrok tunnel using ngrok-rs and hyper.

add cargo-doc-ngrok

---

cargo-doc-ngrok/Cargo.toml

Not sure how this made it through CI the first time.

cargo-doc-ngrok: bump ngrok version

---

muxado/Cargo.toml
muxado/src/stream_manager.rs
muxado/src/stream_output.rs

Seems that this was unneeded!
Thanks to @bender-ngrok for pointing it out!

muxado: remove unsafe_unpinned

---

ngrok/src/config/oauth.rs

ngrok: expose oauth client id/secret setters

---

ngrok/README.md

update readme with intro to ngrok-rs.

update ngrok-rs README

---

ngrok/Cargo.toml
ngrok/src/session.rs

This brings it in-line with ngrok-go
Resolves #81

ngrok: send the UserAgent when authenticating

---

ngrok/src/online_tests.rs

Ran this [20 times in a row](https://github.com/ngrok/ngrok-rs/actions/runs/4661982577) and didn't see the circuit-breaker test fail. I was seeing about 1 in 3 fail the past two days otherwise (usually with an EOF error). This PR stops issuing new request batches once it sees a 503 response indicating that circuit breaking has kicked in, avoiding a flood of too many requests.

make circuit_breaker test more resilient

---

ngrok/CHANGELOG.md
ngrok/Cargo.toml
ngrok/README.md

update changelog and readme

---

CODE_OF_CONDUCT.md

Copied from our documentation repo.

misc: add code of conduct

---

ngrok/Cargo.toml
ngrok/src/config/common.rs
ngrok/src/config/http.rs
ngrok/src/internals/proto.rs
ngrok/src/online_tests.rs

Resolves [#22193](https://github.com/ngrok-private/ngrok/issues/22193)
This PR adds the UserAgentFilter module to ngrok-rust.
To test the module locally:
```bash
mkdir hello-ngrok
cd hello-ngrok
cargo init
cargo add ngrok -F axum
cargo add axum
cargo add tokio -F rt-multi-thread -F macros
```
```rs
use axum::{routing::get, Router};
use ngrok::prelude::*;
use std::error::Error;
#[tokio::main]
async fn main() -> Result<(), Box<dyn Error>> {
// build our application with a route
let app = Router::new().route("/", get(|| async { "Hello from ngrok-rust!" }));
// listen on localhost:8000
// axum::Server::bind(&"0.0.0.0:8000".parse().unwrap())
//  .serve(app.into_make_service())
//  .await?;
// Ok(())
// listen on ngrok ingress (i.e. https://myapp.ngrok.dev)
let listener = …
```

add UserAgentFilter module

---

ngrok/src/config/common.rs
ngrok/src/config/http.rs
ngrok/src/config/labeled.rs
ngrok/src/config/oauth.rs
ngrok/src/config/oidc.rs
ngrok/src/config/tcp.rs
ngrok/src/config/tls.rs
ngrok/src/session.rs

More or less the same change as ngrok/ngrok-go#133.
Add the final destination links. ~I'll run a permalinking script after we've~
~agreed on the permalinks themselves.~ Per the updates in ngrok/ngrok-go#133, Product will handle the redirects, and these links are final.

Add and update doc links

---

.github/workflows/stale-issue.yml

Add some automation, based on: https://docs.github.com/en/actions/managing-issues-and-pull-requests/closing-inactive-issues

add stale-issue project workflow

---

ngrok/Cargo.toml

picking up `TrafficPolicy` changes so they can be propagated to the other SDKs

bump version to 0.14.0-pre.14

---

.gitignore
cargo-doc-ngrok/Cargo.toml
cargo-doc-ngrok/src/main.rs
muxado/Cargo.toml
ngrok/Cargo.toml
ngrok/examples/axum.rs
ngrok/examples/labeled.rs
ngrok/examples/tls.rs
ngrok/src/conn.rs
ngrok/src/forwarder.rs
ngrok/src/online_tests.rs
ngrok/src/proxy_proto.rs
ngrok/src/session.rs
ngrok/src/tunnel.rs
ngrok/src/tunnel_ext.rs

Dependency update pt.2 electric boogaloo
- Update tokio
- Pulls in Josh RC's commits from https://github.com/ngrok/ngrok-rust/pull/137
- Fix a couple other minor import usages since those commits were created
- Bump crate versions

update more dependencies
