muxado/src/codec.rs
muxado/src/frame.rs
muxado/src/session.rs
muxado/src/stream_manager.rs
ngrok/Cargo.toml
ngrok/examples/axum.rs
ngrok/examples/connect.rs
ngrok/examples/labeled.rs
ngrok/examples/tls.rs
ngrok/src/config/common.rs
ngrok/src/config/http.rs
ngrok/src/config/labeled.rs
ngrok/src/config/oauth.rs
ngrok/src/config/oidc.rs
ngrok/src/config/tcp.rs
ngrok/src/config/tls.rs
ngrok/src/internals/raw_session.rs
ngrok/src/lib.rs
ngrok/src/session.rs
ngrok/src/tunnel.rs

Makes the following changes:
* Inverts the tunnel builders such that they hold a clone of the session.
This lets the builders start themselves. By cloning the session, they're also detached from the original session's lifetime, and can be passed around to start tunnels from a common configuration.
* Adds multiple tunnel types with minimal interfaces
This prevents the caller from trying to, say, get the URL of a labeled tunnel that doesn't know its URL.
* Adds a `TunnelBuilder` trait.
As with the other traits added, might be a bit controversial. But could be handy for anyone wanting to take a generic tunnel config and use it to repeatedly produce tunnels, without caring too much about how they're configured. This trait also defines the `Tunnel` type that the builder produces.
* Adds some …

Post-review API changes

---

muxado/Cargo.toml
muxado/src/lib.rs
muxado/src/window.rs

* removes unneeded features
* no more panics on window underflow
It's possible that these are indicative of *another* bug, but we might have better luck finding it if it doesn't cause a panic here. (#29)

muxado: some minor cleanup

---

ngrok/src/internals/rpc.rs

I broke this in the big protocol structure change. Whoops.

ngrok: fix rpc json representation

---

flake.lock
ngrok/examples/mingrok.rs
ngrok/src/lib.rs
ngrok/src/tunnel_ext.rs

I'm also using this as an excuse to play around with tracing/fields/etc. again.
This is what the mingrok logs look like when you have debug enabled for the tunnel module:
```
RUST_LOG=ngrok::tunnel=debug,ngrok=info,mingrok=info cargo run --example mingrok localhost:12345
Compiling muxado v0.1.0 (/home/josh/src/github.com/ngrok/ngrok-rs/muxado)
Compiling ngrok v0.1.0 (/home/josh/src/github.com/ngrok/ngrok-rs/ngrok)
Finished dev [unoptimized + debuginfo] target(s) in 10.05s
Running `target/debug/examples/mingrok 'localhost:12345'`
2022-12-21T19:14:30.900010Z  INFO mingrok: started tunnel, url: "https://3b74b4b29a73.ngrok.app", forwards_to: "localhost:12345"
at ngrok/examples/mingrok.rs:25
2022-12-21T19:14:34.481864Z  WARN ngrok::tunnel_ext: error establishing local connection, error: …
```

ngrok: add tunnel extension to allow connection forwarding

---

flake.nix

Tired of running this big ol' clippy + fmt command by hand, and tired of committing stuff that CI yells at me about.
The pre-commit hook is opt-in, so you can skip it entirely if you want. You have to re-run the `setup-hooks` command if we change the contents of the hook, but since it uses the `PATH` to find cargo & co, it shouldn't need to be re-run if we just update toolchain versions and such.

nix: add some common hooks and helpers

---

.github/workflows/ci.yml
ngrok/src/config/http.rs
ngrok/src/config/labeled.rs
ngrok/src/config/oidc.rs
ngrok/src/config/tcp.rs
ngrok/src/config/tls.rs
ngrok/src/config/webhook_verification.rs
ngrok/src/internals/proto.rs
ngrok/src/internals/raw_session.rs
ngrok/src/internals/rpc.rs
ngrok/src/session.rs

I'm rolling up any protocol changes needed to get #38 working here to keep things somewhat organized.
For the most part, this is just making sure that these structs I added match the json representation generated by protoc, which annoyingly is *completely different* from the hand-written Go structs. This means that all of their fields get defaulted and omitted if they're default, as well as snake_cased, *except* for the `Headers::add_parsed` field, which is inexplicably camelCase in the proto definition.

tunnel proto fixes

---

.gitignore
ngrok/CHANGELOG.md
ngrok/Cargo.toml
ngrok/README.md
ngrok/UPGRADING.md

Still working on the upgrading guide.
We're going to start at v0.7.0 since the current `ngrok` crate on crates.io is at v0.6.0, and we don't want to break users. A minor version bump reflects a breaking change pre-1.0, so they won't accidentally switch from the wrapper to our new crate.

Prepare for release on crates-io

---

flake.nix
ngrok/Cargo.toml
ngrok/src/tunnel.rs

`net: Enables tokio::net types such as TcpStream, UnixStream and UdpSocket, as well as (on Unix-like systems) AsyncFd and (on FreeBSD) PollAio.` https://docs.rs/tokio/latest/tokio/
Also add `libiconv` for darwin in nix, so don't have to use homebrew's.

add tokio "net" feature to support tunnel_ext for cargo users

---

ngrok/examples/axum.rs
ngrok/src/config/http.rs
ngrok/src/internals/proto.rs
ngrok/src/online_tests.rs

Also adds a tls online test, `Scheme::from_str`, and a `forwards_to` example.

handle non-camel-case in tls and tcp deserialization

---

.github/workflows/ci.yml
.github/workflows/release.yml
flake.lock
flake.nix
ngrok/README.md

Alright, I'm reasonably happy with this now. Semver checks now happen before PR merge, and once it hits master, it'll always try to publish, and if the publish succeeds, it'll add a git tag for us.
So all we have to do to publish is make a PR with a version bump!

ci: Add release checks and jobs

---

.github/workflows/ci.yml
.github/workflows/release.yml

Bumping my direnv action to 0.7, which now includes nix installation and direnv cache/import/export. Might hopefully speed things along a little bit, since we'll be fetching a single big archive from github rather than lots of little ones from the nixos cache.

ci: cache nix dependencies

---

muxado/src/session.rs
muxado/src/typed.rs
ngrok/Cargo.toml
ngrok/examples/mingrok.rs
ngrok/src/config/http.rs
ngrok/src/internals/proto.rs
ngrok/src/internals/raw_session.rs
ngrok/src/session.rs
ngrok/src/tunnel_ext.rs

Not 100% happy with the `Fn` rather than `FnMut` constraint, but we can
probably loosen that later if it becomes too much of an issue.
I'm not sure if the fields to the update command actually get sent, or
if they're just some old meaningless cruft that we don't actually use
anymore.
Still need to do the local connection state callbacks, but I think those
are separate enough to warrant a different PR.
As an aside, I also noticed that the session/tunnels don't stop if there are
no reachable handles to them in consumer code. Like in the `mingrok`
example, both the session and tunnel stick around after a restart, and
even if you close the tunnel, the session is *still* hanging out. Going
to file a bug for that - probably something missed in the restart logic,
if not deeper.

ngrok: add support for dashboard command handlers

---

muxado/Cargo.toml
muxado/src/cancellation_test.rs
muxado/src/heartbeat.rs
muxado/src/lib.rs
muxado/src/session.rs
muxado/src/stream.rs
muxado/src/stream_manager.rs

Created a fancy-pants waitgroup implementation just for this purpose. I expect to make a similar change to the ngrok crate to shut down its background tasks as well once all tunnels and the session is dropped.

muxado: cancel tasks when all references are dropped

---

cargo-doc-ngrok/Cargo.toml
muxado/CHANGELOG.md
muxado/Cargo.toml
muxado/src/heartbeat.rs
ngrok/CHANGELOG.md
ngrok/Cargo.toml
ngrok/src/internals/raw_session.rs
ngrok/src/session.rs
ngrok/src/tunnel.rs

Basically the same change as muxado cancellation.
Tunnels already having a reference to the session ended up being really
convenient.
Resolves #57

ngrok: detect tunnel/session liveness and shutdown background tasks

---

.github/workflows/ci.yml
muxado/CHANGELOG.md
muxado/Cargo.toml
muxado/examples/heartbeat.rs
muxado/src/heartbeat.rs
ngrok/Cargo.toml
ngrok/src/internals/raw_session.rs
ngrok/src/session.rs

~~Not entirely happy with the mutex here. Might drop it back to non-mut/`Fn` rather than `&mut`/`FnMut`. It's fine for the single-restarting-session case, but cloning the builder and starting multiple concurrent sessions with it could cause problems since they'd be fighting to lock the handler.~~ No more mutex!
Consumers will have to deal with interior mutability themselves, but that seems fine-ish. It at least matches the command handlers.

ngrok/muxado: add a user-definable heartbeat handler

---

cargo-doc-ngrok/Cargo.toml
flake.nix
ngrok/Cargo.toml
ngrok/examples/mingrok.rs
ngrok/src/tunnel_ext.rs

Allows using named pipes on windows, e.g. `\\.\pipe\ngrok_pipe`

add windows pipe support

---

muxado/Cargo.toml
ngrok/Cargo.toml

Apparently the tests/examples all brought it in, so its absence wasn't
noticed until @nikolay-ngrok tried using it elsewhere.

deps: require the tokio rt feature in ngrok and muxado

---

ngrok/src/session.rs

Kinda rough/subject to change in the future, but at least it'll give us
a way to "stack" abstraction types and versions, like js, the agent,
etc.
The protocol semantics are almost certain to get an overhaul once we
figure out the "minimum version enforcement" feature, but for now, this
seems "good enough."

ngrok: add support for "child" client types/versions

---

muxado/src/heartbeat.rs
ngrok/src/internals/raw_session.rs
ngrok/src/session.rs
ngrok/src/tunnel.rs

There are some spots (notably TunnelInner::drop) where we expect to be
in a tokio runtime context, and blindly call `tokio::spawn`, which
panics outside of the runtime.
Now, we grab a handle to the runtime at session (or heartbeat) startup,
and squirrel it away to use for future spawning, just in case it
happens outside of tokio.
This is probably the first step in decoupling from tokio entirely and
making both ngrok and muxado truly generic over the IO backend and
executor. That'll be a Big Change though, and might not happen until we
really need it.

all: slightly decouple from the current execution context

---

cargo-doc-ngrok/Cargo.toml
ngrok/Cargo.toml
ngrok/src/session.rs

Modeling off of [ngrok-go](https://github.com/ngrok/ngrok-go/blob/73d54eba1716e8889b7034f8ecd8071d69f8691a/session.go#L192).
Semver check fails, but this is a currently undocumented method, hopefully ok?
May want it to be `Option<Vec<String>>` to remove the `impl Into` so don't have to qualify a `None` like `None::<Vec<String>>`. Loses the flexibility, but makes the common case simpler.

Add comment to client_info

---

ngrok/Cargo.toml
ngrok/src/tunnel.rs

This will allow checking if reconnect is cancelled, so client can know if session is closing.

Attach source to reconnect error

---

.github/workflows/ci.yml
Cargo.toml
flake.lock
muxado/src/stream_manager.rs
ngrok/CHANGELOG.md
ngrok/Cargo.toml

- Explicitly adding the `Win32_Foundation` feature of `windows-sys` to resolve https://github.com/ngrok/ngrok-rust/issues/99
- Adds a Windows build+test CI stage, removes long-tests from test-nix (but not test-stable) to be less-likely to trip packet blocking
- Updates nix `flake.lock`to move from rust `1.68` to `1.72` to get a clippy of at least `1.70` to pick up the now-required [let_with_type_underscore](https://rust-lang.github.io/rust-clippy/master/index.html#/let_with_type_underscore) lint
- Adds `resolver = "2"` to root `Cargo.toml` to remove resulting warn from the rust upgrade
- Removes a `mut` in [stream_manager.rs](https://github.com/ngrok/ngrok-rust/pull/101/files#diff-509c841b05c2bffa9f0cd523753190abc90adb8fef8d858bd881fc3951aff503) to appease the new clippy

Add feature Win32_Foundation, update nix for rust 1.72

---

cargo-doc-ngrok/Cargo.toml
ngrok/CHANGELOG.md
ngrok/Cargo.toml
ngrok/README.md
ngrok/src/internals/proto.rs
ngrok/src/internals/raw_session.rs
ngrok/src/lib.rs
ngrok/src/online_tests.rs
ngrok/src/session.rs

Resolves ngrok-private/ngrok#21498
Adds an `ErrResp` proto struct and an `NgrokError` trait.
The `ErrResp` gets parsed from the stringly-typed error message that
comes from tunnel protocol RPC calls, and holds both the messge and code
fields. The `NgrokError` trait allows us to bubble these fields up
through the `thiserror` wrappings to make it easier to get the ngrok
code/message at the top-level, i.e. `ConnectError` and `RpcError`.

ngrok: parse error responses and surface the msg and code

---

ngrok/CHANGELOG.md
ngrok/Cargo.toml
ngrok/src/internals/proto.rs

I got this wrong - we should be including the prefix to the error codes
after all. See [this thread](https://github.com/ngrok/ngrok-go/pull/112#discussion_r1297876439) for context.

ngrok: don't trim the ERR_NGROK prefix from error codes

---

cargo-doc-ngrok/Cargo.toml
cargo-doc-ngrok/src/main.rs
ngrok/Cargo.toml
ngrok/src/config/http.rs
ngrok/src/config/labeled.rs
ngrok/src/config/oauth.rs
ngrok/src/config/oidc.rs
ngrok/src/config/tcp.rs
ngrok/src/config/tls.rs
ngrok/src/internals/proto.rs
ngrok/src/internals/raw_session.rs
ngrok/src/lib.rs
ngrok/src/online_tests.rs
ngrok/src/session.rs

Resolves #95
This also opens the way to allow builder methods to return `Results`, as
the builder won't be consumed in the event of bad input. Then, we can
push some validation to build time rather than connect time.
Combining this with a few other breaking changes, namely:
* No more `Error` stutter
* Validate the server addr at config time
* Validate the heartbeat config at config time
* Remove the server addr/heartbeat errors from the connect error enum
* Split the server addr into host/port when passing them to the connector

ngrok: switch to mutable builder pattern

---

ngrok/Cargo.toml
ngrok/src/session.rs

Resolves ngrok-private/ngrok#21250
Adds a `SessionBuilder::proxy_url` method that sets the session up to
connect via either an http or a socks5 proxy. As with `ngrok-go`, these
are mutually-exclusive with the `connector` and will override that
setting.
~~Errors from unsupported proxy schemes, like in `ngrok-go`, are deferred
to connect time. This isn't great, but we're kinda stuck with it since
builder method errors will consume the builder without hope of graceful
recovery, which is *also* bad. Might be time to re-evaluate #95.~~
Rebased this on #107, so we get config-time errors for unsupported proxies :tada:

ngrok: support connecting through either http or socks5 proxies

---

ngrok/Cargo.toml
ngrok/examples/mingrok.rs
ngrok/src/tunnel.rs
ngrok/src/tunnel_ext.rs

Switches us from the explicit tcp, http, and pipe forwarding methods to
accepting a URL. This should make it easier for us to update what
protocols we support without having to change the public API.
Eventually, we'll also be able to forward smarter with regards to tls,
proxyproto, etc. like the agent, but that'll come later.

Switch to forwarding based on URL and add TLS forwarding

---

ngrok/Cargo.toml
ngrok/src/conn.rs
ngrok/src/internals/proto.rs
ngrok/src/lib.rs
ngrok/src/online_tests.rs
ngrok/src/proxy_proto.rs
ngrok/src/session.rs
ngrok/src/tunnel_ext.rs

Currently, we ignore proxy protocol settings in our tunnels. This means that,
for tls and https connections that are terminated at the ngrok edge, the
incoming connections look like `ProxyProtoStream(PlainTextStream)`. When we
then terminate tls to the backend/upstream/whatever you want to call it, the
final stream looks like `TlsStream(ProxyProtoStream(PlainTextStream))`, where
it's expected to look like `ProxyProtoStream(TlsStream(PlainTextStream))`,
since proxy-protocol is a lower layer than TLS.
To that end, this change plumbs the proxy-proto setting through to the endpoint
connection object, reads the header out of the stream, and then makes sure to
write that to the upstream _first_ before terminating TLS.

Forward proxy-protocol correctly to tls backends

---

ngrok/Cargo.toml
ngrok/src/proxy_proto.rs
ngrok/src/tunnel_ext.rs

If an inbound request is too small, no `poll_write` is issued to the outbound proxy stream by `copy_bidirectional`, so the data is never written to the inner stream. This adds returns `Ready` from remainder copying without condition, which resolves issue in an `ngrok-python` proxy test.

Make sure Ready is returned on proxy_proto remainder polling

---

ngrok/src/internals/proto.rs

Adds `Error` impls for `&` references, `Box`es, and `Arc`s where the type they
point to implements `Error`.

ngrok: add Error impls for common pointer types

---

ngrok/src/config/common.rs
ngrok/src/config/headers.rs
ngrok/src/config/http.rs
ngrok/src/config/labeled.rs
ngrok/src/config/tcp.rs
ngrok/src/config/tls.rs

This is now implemented by our request header middleware upstream, but this
adds some convenience and docs to it.
Users can call `http_builder.host_header_rewrite(true);` to have it set
automatically on `listen_and_forward` calls, and it also points out the
`.request_header(...)` approach to setting specific values.
Also canonicalizes (lowercases, really) header keys to make sure we aren't
sending multiple values for the same differently-cased "Host" header.

ngrok: auto-rewrite the http host header

---

ngrok/examples/axum.rs
ngrok/examples/labeled.rs
ngrok/src/config/common.rs
ngrok/src/config/http.rs
ngrok/src/config/labeled.rs
ngrok/src/config/tcp.rs
ngrok/src/config/tls.rs
ngrok/src/internals/proto.rs
ngrok/src/internals/raw_session.rs
ngrok/src/session.rs
ngrok/src/tunnel.rs

We'd like to be able specify http2 when building an http tunnel
Add `app_protocol` to the builder and plumb the `forwards_proto` into the session rpc.
Run an example with the http2 app protocol and confirm the correct `forwardsProto` was set to `"http2"` or `""` .

feat: add app protocol 

---

ngrok/src/config/common.rs
ngrok/src/conn.rs
ngrok/src/session.rs
ngrok/src/tunnel_ext.rs

If the upstream is a normal HTTPs server, it expects to have http/2 negotiated
via alpn. If alpn isn't provided, it will assume http/1.1. If our edge proxy is
sending down http/2 because `app_protocol` was specified, this results in a
protocol mismatch, and invalid requests/responses will be seen.
This ensures that the negotiation happens as expected.

ngrok: set the alpn field when app_protocol is specified

---

cargo-doc-ngrok/src/main.rs
flake.lock
muxado/examples/server.rs
muxado/src/session.rs
muxado/src/stream.rs
ngrok/Cargo.toml
ngrok/src/internals/proto.rs
ngrok/src/online_tests.rs
ngrok/src/session.rs
ngrok/src/tunnel_ext.rs

The big one here is `async-rustls`, which was deprecated wholesale in favor of `futures-rustls`. Most of the rest are pretty rote.

Upgrade several dependencies

---

flake.lock
muxado/examples/heartbeat.rs
muxado/examples/subscriber.rs
muxado/src/heartbeat.rs
muxado/src/stream.rs
ngrok/examples/mingrok.rs
ngrok/src/config/http.rs
ngrok/src/config/tls.rs
ngrok/src/session.rs
ngrok/src/tunnel_ext.rs

Fixes nix env on darwin: https://github.com/obi1kenobi/cargo-semver-checks/pull/647

update nix for cargo-semver-checks 0.29

---

ngrok/Cargo.toml
ngrok/examples/connect.rs
ngrok/src/online_tests.rs
ngrok/src/session.rs
ngrok/src/tunnel_ext.rs

Allow this on SessionBuilder:
- `.root_cas("trusted")`
- `.root_cas("host")`
- `.root_cas("/path/to/cert")`
Similar to: https://ngrok.com/docs/ngrok-agent/config/#root_cas

add root_cas

---

flake.nix

For nix-based workflow, we often install language servers within the project we are working on. By including the language server here, someone using nix would have all the tooling they need just using the included flake. Additionally, it helps keep the LSP version in sync with the version of rust in the flake.
I'm using the Helix text editor to detect the presence of the rust-analyzer LSP. It does this by simply checking that `rust-analyzer` is in the current path.
I also validated that the LSP works by opening one of the example files.

add rust language server to flake

---

ngrok/src/config/http.rs
ngrok/src/config/labeled.rs
ngrok/src/config/tcp.rs
ngrok/src/config/tls.rs
ngrok/src/internals/proto.rs
ngrok/src/online_tests.rs

add bindings mix-in to ngrok-rust

add bindings to ngrok-rust

---

cargo-doc-ngrok/Cargo.toml
muxado/Cargo.toml
ngrok/Cargo.toml

Bumps the package versions so that the next merge to main will publish new crates. I only bumped a patch version since all I did was update dependencies.

publish new crates

---

ngrok/CHANGELOG.md
ngrok/Cargo.toml
ngrok/examples/axum.rs
ngrok/examples/connect.rs
ngrok/src/config/common.rs
ngrok/src/config/http.rs
ngrok/src/config/labeled.rs
ngrok/src/config/tcp.rs
ngrok/src/config/tls.rs
ngrok/src/internals/proto.rs

1. Clone the repo and checkout this branch
2. Copy/pasta the below code (use the relative path of the ngrok-rust sdk you cloned as the path of the ngrok crate in Cargo.toml)
3. `cargo build`
4. `cargo run`
5. Start a server on whatever two ports you'd like (I use `python -m http.server 3000 && python -m http.server 8000)
6. Open the url of your ngrok reserved domain in the browser
7. Observe that both ports (3000 and 8000) show the http requests!
```rust
#![deny(warnings)]
use axum::{Router, routing::get};
use std::net::SocketAddr;
use url::Url;
use ngrok::config::ForwarderBuilder;
#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error + Send + Sync>> {  
// Create Axum app
let app = Router::new()
.route("/", get(|| async { "Hello from Axum!" }));
// Spawn Axum server
let …
```

feat: Enable endpoint pooling configuration

---

cargo-doc-ngrok/Cargo.toml
ngrok/CHANGELOG.md
ngrok/Cargo.toml
ngrok/src/online_tests.rs
ngrok/src/session.rs
ngrok/src/tunnel_ext.rs

Resolves #158 
```rust
use ngrok::config::ForwarderBuilder;
use ngrok::tunnel::EndpointInfo;
use url::Url;
#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error + Send + Sync>> {
let _ = rustls::crypto::aws_lc_rs::default_provider().install_default();
connect_http_proxy().await?;
Ok(())
}
async fn connect_http_proxy() -> Result<(), Box<dyn std::error::Error + Send + Sync>> {
// Set up ngrok tunnel
let sess = ngrok::Session::builder()
.authtoken_from_env()
.proxy_url(Url::parse("/* proxy url */").unwrap())?
.root_cas("/* path to proxy certificate */")?
.connect()
.await?
.http_endpoint()
.domain("/* your reserved ngrok domain */")
.listen_and_forward(Url::parse("/* your server url */").unwrap())
.await?;
println!("Ingress established at {:#?}", sess.url());
// Wait …
```

chore: Remove hyper_proxy crate

---

Cargo.lock
ngrok/Cargo.toml
ngrok/src/online_tests.rs

This verifies an http connect proxy works, and since we're making changes around there, it's worth having a basic test to validate it functions.

Add an online test for an http connect proxy_url

---

.github/workflows/release.yml

These commands pass locally but fail in GHA because it interprets no results from grep as exit code 1 and fails the action. Instead this change will return true if grep fails and set result to an empty string. This allows the next if condition to run. In an empty string case we won't exit early and will push the new package.

[actions] Make sure grep doesn't return an error otherwise GHA will fail
